#include "Tad_busca/busca.h"

int main() {
    Arvore raiz;
    Tdocumento doc;
    TBusca busca;
    Inicializar_Arvore(&raiz);
    inicializaDoc(&doc);
    InicializaBusca(&busca);
    // Inserção de palavras na árvore
    Insere_Palavra_Arvore(&raiz, "carro", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "casa", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "cadeira", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "computador", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "laranja", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "livro", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "mesa", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "celular", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "teclado", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "mouse", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "lapis", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "abacate", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "banana", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "abacaxi", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "laranja", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "morango", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "limao", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "manga", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "uva", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "pera", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "laranja", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "kiwi", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "manga", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "carro", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "manga", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "carro", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "casa", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "cadeira", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "computador", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "livro", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "mesa", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "celular", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "teclado", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "mouse", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "lapis", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "abacate", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "banana", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "abacaxi", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "laranja", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "morango", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "limao", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "manga", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "uva", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "pera", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "kiwi", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "manga", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "carro", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "manga", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "abacate", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "banana", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "laranja", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "limao", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "abacaxi", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "uva", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "laranja", 2, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "pera", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "kiwi", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "abacate", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "banana", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "laranja", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "limao", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "abacaxi", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "uva", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "pera", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "kiwi", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "manga", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "abacate", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "banana", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "laranja", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "limao", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "abacaxi", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "uva", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "pera", 2, "arquivo2.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "kiwi", 3, "arquivo3.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "monitor", 1, "arquivo1.txt", &doc);
    Insere_Palavra_Arvore(&raiz, "laranja", 3, "arquivo1.txt", &doc);

    // Impressão em ordem das palavras na árvore
    Ordem(raiz);
    printf("quantidade de docs: %d\n", quantidadeDocs(&doc));
    //imprimeDoc(&doc, 1);
    //imprimeDoc(&doc, 2);
    //imprimeDoc(&doc, 3);
    // Busca por palavra
    printf("\nBusca por palavra: manga\n");
    calculoRelevancia(raiz, "manga", &doc, &busca);
    printf("\nBusca por palavra: carro\n");
    calculoRelevancia(raiz, "carro", &doc, &busca);
    printf("\nBusca por palavra: casa\n");
    calculoRelevancia(raiz, "casa", &doc, &busca);
    printf("\nBusca por palavra: mesa\n");
    calculoRelevancia(raiz, "mesa", &doc, &busca);
    printf("\nBusca por palavra: teclado\n");
    calculoRelevancia(raiz, "teclado", &doc, &busca);
    printf("\nBusca por palavra: mouse\n");
    calculoRelevancia(raiz, "mouse", &doc, &busca);
    printf("\nBusca por palavra: monitor\n");
    calculoRelevancia(raiz, "monitor", &doc, &busca);
    printf("\nBusca por palavra: laranja\n");
    calculoRelevancia(raiz, "laranja", &doc, &busca);
    return 0;
}
